// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221221012334_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Backend.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfApproval")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Approval");
                });

            modelBuilder.Entity("Backend.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.CTEForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ApprovalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChairApprovalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeanApprovalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Department")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExchangeCoordinatorApprovalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FacultyOfAdministrationBoardApprovalId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostUniversityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IDNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PDF")
                        .HasColumnType("bytea");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ToDoItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChairApprovalId");

                    b.HasIndex("DeanApprovalId");

                    b.HasIndex("ExchangeCoordinatorApprovalId");

                    b.HasIndex("FacultyOfAdministrationBoardApprovalId");

                    b.HasIndex("StudentId");

                    b.ToTable("CTEForms");
                });

            modelBuilder.Entity("Backend.Entities.DomainUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("DomainUsers");
                });

            modelBuilder.Entity("Backend.Entities.EquivalenceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ExemptedCourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("HostCourseCode")
                        .HasColumnType("text");

                    b.Property<double>("HostCourseECTS")
                        .HasColumnType("double precision");

                    b.Property<string>("HostCourseName")
                        .HasColumnType("text");

                    b.Property<string>("HostUniversityName")
                        .HasColumnType("text");

                    b.Property<Guid?>("InstructorApprovalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("boolean");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StudentId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Syllabus")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ExemptedCourseId");

                    b.HasIndex("InstructorApprovalId");

                    b.HasIndex("StudentId1");

                    b.ToTable("EquivalenceRequests");
                });

            modelBuilder.Entity("Backend.Entities.ExemptedCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BilkentCredits")
                        .HasColumnType("integer");

                    b.Property<string>("CourseCode")
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .HasColumnType("text");

                    b.Property<int>("CourseType")
                        .HasColumnType("integer");

                    b.Property<double>("ECTS")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ExemptedCourse");
                });

            modelBuilder.Entity("Backend.Entities.LoggedEquivalentCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExemptedCourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("HostCourseCode")
                        .HasColumnType("text");

                    b.Property<double>("HostCourseECTS")
                        .HasColumnType("double precision");

                    b.Property<string>("HostCourseName")
                        .HasColumnType("text");

                    b.Property<string>("HostSchool")
                        .HasColumnType("text");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExemptedCourseId");

                    b.ToTable("LoggedEquivalentCourses");
                });

            modelBuilder.Entity("Backend.Entities.LoggedTransferredCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LoggedTransferredCourses");
                });

            modelBuilder.Entity("Backend.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid?>("DomainUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DomainUserId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MessageSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientUsername")
                        .HasColumnType("text");

                    b.Property<string>("SenderUsername")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DomainUserId");

                    b.HasIndex("DomainUserId1");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Backend.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("read")
                        .HasColumnType("boolean");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Backend.Entities.PlacedStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CGPA")
                        .HasColumnType("double precision");

                    b.Property<string>("ExchangeSchool")
                        .HasColumnType("text");

                    b.Property<double>("ExchangeScore")
                        .HasColumnType("double precision");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsPlaced")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PreferredSchools")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlacedStudents");
                });

            modelBuilder.Entity("Backend.Entities.PlacementTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("ExcelFile")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PlacementTables");
                });

            modelBuilder.Entity("Backend.Entities.PreApprovalForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ApprovalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Department")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExchangeCoordinatorApprovalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FacultyAdministrationBoardApprovalId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostUniversityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IDNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PDF")
                        .HasColumnType("bytea");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ToDoItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeCoordinatorApprovalId");

                    b.HasIndex("FacultyAdministrationBoardApprovalId");

                    b.HasIndex("StudentId");

                    b.ToTable("PreApprovalForms");
                });

            modelBuilder.Entity("Backend.Entities.RequestedCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ECTS")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("RequestedCourseGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestedCourseGroupId");

                    b.ToTable("RequestedCourse");
                });

            modelBuilder.Entity("Backend.Entities.RequestedCourseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreApprovalFormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedExemptedCourseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PreApprovalFormId");

                    b.HasIndex("RequestedExemptedCourseId");

                    b.ToTable("RequestedCourseGroup");
                });

            modelBuilder.Entity("Backend.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CascadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("ExchangeCoordinatorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeCoordinatorId");

                    b.HasIndex("StudentId");

                    b.ToTable("ToDoItems");
                });

            modelBuilder.Entity("Backend.Entities.TransferredCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ECTS")
                        .HasColumnType("double precision");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TransferredCourseGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransferredCourseGroupId");

                    b.ToTable("TransferredCourse");
                });

            modelBuilder.Entity("Backend.Entities.TransferredCourseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CTEFormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExemptedCourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoggedTransferredCourseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CTEFormId");

                    b.HasIndex("ExemptedCourseId");

                    b.HasIndex("LoggedTransferredCourseId");

                    b.ToTable("TransferredCourseGroup");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Admin", b =>
                {
                    b.HasBaseType("Backend.Entities.DomainUser");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Backend.Entities.CourseCoordinatorInstructor", b =>
                {
                    b.HasBaseType("Backend.Entities.DomainUser");

                    b.Property<bool>("IsCourseCoordinator")
                        .HasColumnType("boolean");

                    b.ToTable("CourseCoordinatorInstructors");
                });

            modelBuilder.Entity("Backend.Entities.DeanDepartmentChair", b =>
                {
                    b.HasBaseType("Backend.Entities.DomainUser");

                    b.Property<bool>("IsDean")
                        .HasColumnType("boolean");

                    b.ToTable("DeanDepartmentChairs");
                });

            modelBuilder.Entity("Backend.Entities.ExchangeCoordinator", b =>
                {
                    b.HasBaseType("Backend.Entities.DomainUser");

                    b.ToTable("ExchangeCoordinators");
                });

            modelBuilder.Entity("Backend.Entities.OISEP", b =>
                {
                    b.HasBaseType("Backend.Entities.DomainUser");

                    b.ToTable("OISEPs");
                });

            modelBuilder.Entity("Backend.Entities.Student", b =>
                {
                    b.HasBaseType("Backend.Entities.DomainUser");

                    b.Property<double>("CGPA")
                        .HasColumnType("double precision");

                    b.Property<int>("EntranceYear")
                        .HasColumnType("integer");

                    b.Property<string>("ExchangeSchool")
                        .HasColumnType("text");

                    b.Property<double>("ExchangeScore")
                        .HasColumnType("double precision");

                    b.Property<string>("PreferredSchools")
                        .HasColumnType("text");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Backend.Entities.CTEForm", b =>
                {
                    b.HasOne("Backend.Entities.Approval", "ChairApproval")
                        .WithMany()
                        .HasForeignKey("ChairApprovalId");

                    b.HasOne("Backend.Entities.Approval", "DeanApproval")
                        .WithMany()
                        .HasForeignKey("DeanApprovalId");

                    b.HasOne("Backend.Entities.Approval", "ExchangeCoordinatorApproval")
                        .WithMany()
                        .HasForeignKey("ExchangeCoordinatorApprovalId");

                    b.HasOne("Backend.Entities.Approval", "FacultyOfAdministrationBoardApproval")
                        .WithMany()
                        .HasForeignKey("FacultyOfAdministrationBoardApprovalId");

                    b.HasOne("Backend.Entities.Student", null)
                        .WithMany("CTEForms")
                        .HasForeignKey("StudentId");

                    b.Navigation("ChairApproval");

                    b.Navigation("DeanApproval");

                    b.Navigation("ExchangeCoordinatorApproval");

                    b.Navigation("FacultyOfAdministrationBoardApproval");
                });

            modelBuilder.Entity("Backend.Entities.DomainUser", b =>
                {
                    b.HasOne("Backend.Entities.AppUser", "IdentityUser")
                        .WithOne("DomainUser")
                        .HasForeignKey("Backend.Entities.DomainUser", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Backend.Entities.EquivalenceRequest", b =>
                {
                    b.HasOne("Backend.Entities.ExemptedCourse", "ExemptedCourse")
                        .WithMany()
                        .HasForeignKey("ExemptedCourseId");

                    b.HasOne("Backend.Entities.Approval", "InstructorApproval")
                        .WithMany()
                        .HasForeignKey("InstructorApprovalId");

                    b.HasOne("Backend.Entities.Student", null)
                        .WithMany("EquivalenceRequestForms")
                        .HasForeignKey("StudentId1");

                    b.Navigation("ExemptedCourse");

                    b.Navigation("InstructorApproval");
                });

            modelBuilder.Entity("Backend.Entities.LoggedEquivalentCourse", b =>
                {
                    b.HasOne("Backend.Entities.ExemptedCourse", "ExemptedCourse")
                        .WithMany()
                        .HasForeignKey("ExemptedCourseId");

                    b.Navigation("ExemptedCourse");
                });

            modelBuilder.Entity("Backend.Entities.Message", b =>
                {
                    b.HasOne("Backend.Entities.DomainUser", null)
                        .WithMany("MessagesReceived")
                        .HasForeignKey("DomainUserId");

                    b.HasOne("Backend.Entities.DomainUser", null)
                        .WithMany("MessagesSent")
                        .HasForeignKey("DomainUserId1");
                });

            modelBuilder.Entity("Backend.Entities.PlacedStudent", b =>
                {
                    b.OwnsOne("Backend.Entities.DepartmentInfo", "Department", b1 =>
                        {
                            b1.Property<Guid>("PlacedStudentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DepartmentName")
                                .HasColumnType("integer")
                                .HasColumnName("DepartmentName");

                            b1.Property<int>("FacultyName")
                                .HasColumnType("integer")
                                .HasColumnName("FacultyName");

                            b1.HasKey("PlacedStudentId");

                            b1.ToTable("PlacedStudents");

                            b1.WithOwner()
                                .HasForeignKey("PlacedStudentId");
                        });

                    b.OwnsOne("Backend.Entities.SemesterInfo", "PreferredSemester", b1 =>
                        {
                            b1.Property<Guid>("PlacedStudentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AcademicYear")
                                .HasColumnType("text");

                            b1.Property<int>("Semester")
                                .HasColumnType("integer");

                            b1.HasKey("PlacedStudentId");

                            b1.ToTable("PlacedStudents");

                            b1.WithOwner()
                                .HasForeignKey("PlacedStudentId");
                        });

                    b.Navigation("Department");

                    b.Navigation("PreferredSemester");
                });

            modelBuilder.Entity("Backend.Entities.PlacementTable", b =>
                {
                    b.OwnsOne("Backend.Entities.DepartmentInfo", "Department", b1 =>
                        {
                            b1.Property<Guid>("PlacementTableId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DepartmentName")
                                .HasColumnType("integer")
                                .HasColumnName("DepartmentName");

                            b1.Property<int>("FacultyName")
                                .HasColumnType("integer")
                                .HasColumnName("FacultyName");

                            b1.HasKey("PlacementTableId");

                            b1.ToTable("PlacementTables");

                            b1.WithOwner()
                                .HasForeignKey("PlacementTableId");
                        });

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Backend.Entities.PreApprovalForm", b =>
                {
                    b.HasOne("Backend.Entities.Approval", "ExchangeCoordinatorApproval")
                        .WithMany()
                        .HasForeignKey("ExchangeCoordinatorApprovalId");

                    b.HasOne("Backend.Entities.Approval", "FacultyAdministrationBoardApproval")
                        .WithMany()
                        .HasForeignKey("FacultyAdministrationBoardApprovalId");

                    b.HasOne("Backend.Entities.Student", null)
                        .WithMany("PreApprovalForms")
                        .HasForeignKey("StudentId");

                    b.Navigation("ExchangeCoordinatorApproval");

                    b.Navigation("FacultyAdministrationBoardApproval");
                });

            modelBuilder.Entity("Backend.Entities.RequestedCourse", b =>
                {
                    b.HasOne("Backend.Entities.RequestedCourseGroup", null)
                        .WithMany("RequestedCourses")
                        .HasForeignKey("RequestedCourseGroupId");
                });

            modelBuilder.Entity("Backend.Entities.RequestedCourseGroup", b =>
                {
                    b.HasOne("Backend.Entities.PreApprovalForm", null)
                        .WithMany("RequestedCourseGroups")
                        .HasForeignKey("PreApprovalFormId");

                    b.HasOne("Backend.Entities.ExemptedCourse", "RequestedExemptedCourse")
                        .WithMany()
                        .HasForeignKey("RequestedExemptedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedExemptedCourse");
                });

            modelBuilder.Entity("Backend.Entities.ToDoItem", b =>
                {
                    b.HasOne("Backend.Entities.ExchangeCoordinator", null)
                        .WithMany("ToDoList")
                        .HasForeignKey("ExchangeCoordinatorId");

                    b.HasOne("Backend.Entities.Student", null)
                        .WithMany("ToDoList")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("Backend.Entities.TransferredCourse", b =>
                {
                    b.HasOne("Backend.Entities.TransferredCourseGroup", null)
                        .WithMany("TransferredCourses")
                        .HasForeignKey("TransferredCourseGroupId");
                });

            modelBuilder.Entity("Backend.Entities.TransferredCourseGroup", b =>
                {
                    b.HasOne("Backend.Entities.CTEForm", null)
                        .WithMany("TransferredCourseGroups")
                        .HasForeignKey("CTEFormId");

                    b.HasOne("Backend.Entities.ExemptedCourse", "ExemptedCourse")
                        .WithMany()
                        .HasForeignKey("ExemptedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.LoggedTransferredCourse", null)
                        .WithMany("TransferredCourseGroups")
                        .HasForeignKey("LoggedTransferredCourseId");

                    b.Navigation("ExemptedCourse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Backend.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Backend.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Backend.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Backend.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Backend.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Entities.Admin", b =>
                {
                    b.HasOne("Backend.Entities.DomainUser", null)
                        .WithOne()
                        .HasForeignKey("Backend.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Entities.CourseCoordinatorInstructor", b =>
                {
                    b.HasOne("Backend.Entities.DomainUser", null)
                        .WithOne()
                        .HasForeignKey("Backend.Entities.CourseCoordinatorInstructor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Backend.Entities.Course", "Course", b1 =>
                        {
                            b1.Property<Guid>("CourseCoordinatorInstructorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CourseCode")
                                .HasColumnType("text");

                            b1.Property<string>("CourseName")
                                .HasColumnType("text");

                            b1.HasKey("CourseCoordinatorInstructorId");

                            b1.ToTable("CourseCoordinatorInstructors");

                            b1.WithOwner()
                                .HasForeignKey("CourseCoordinatorInstructorId");
                        });

                    b.OwnsOne("Backend.Entities.DepartmentInfo", "Department", b1 =>
                        {
                            b1.Property<Guid>("CourseCoordinatorInstructorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DepartmentName")
                                .HasColumnType("integer")
                                .HasColumnName("DepartmentName");

                            b1.Property<int>("FacultyName")
                                .HasColumnType("integer")
                                .HasColumnName("FacultyName");

                            b1.HasKey("CourseCoordinatorInstructorId");

                            b1.ToTable("CourseCoordinatorInstructors");

                            b1.WithOwner()
                                .HasForeignKey("CourseCoordinatorInstructorId");
                        });

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Backend.Entities.DeanDepartmentChair", b =>
                {
                    b.HasOne("Backend.Entities.DomainUser", null)
                        .WithOne()
                        .HasForeignKey("Backend.Entities.DeanDepartmentChair", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Backend.Entities.DepartmentInfo", "Department", b1 =>
                        {
                            b1.Property<Guid>("DeanDepartmentChairId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DepartmentName")
                                .HasColumnType("integer")
                                .HasColumnName("DepartmentName");

                            b1.Property<int>("FacultyName")
                                .HasColumnType("integer")
                                .HasColumnName("FacultyName");

                            b1.HasKey("DeanDepartmentChairId");

                            b1.ToTable("DeanDepartmentChairs");

                            b1.WithOwner()
                                .HasForeignKey("DeanDepartmentChairId");
                        });

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Backend.Entities.ExchangeCoordinator", b =>
                {
                    b.HasOne("Backend.Entities.DomainUser", null)
                        .WithOne()
                        .HasForeignKey("Backend.Entities.ExchangeCoordinator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Backend.Entities.DepartmentInfo", "Department", b1 =>
                        {
                            b1.Property<Guid>("ExchangeCoordinatorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DepartmentName")
                                .HasColumnType("integer")
                                .HasColumnName("DepartmentName");

                            b1.Property<int>("FacultyName")
                                .HasColumnType("integer")
                                .HasColumnName("FacultyName");

                            b1.HasKey("ExchangeCoordinatorId");

                            b1.ToTable("ExchangeCoordinators");

                            b1.WithOwner()
                                .HasForeignKey("ExchangeCoordinatorId");
                        });

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Backend.Entities.OISEP", b =>
                {
                    b.HasOne("Backend.Entities.DomainUser", null)
                        .WithOne()
                        .HasForeignKey("Backend.Entities.OISEP", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Entities.Student", b =>
                {
                    b.HasOne("Backend.Entities.DomainUser", null)
                        .WithOne()
                        .HasForeignKey("Backend.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Backend.Entities.DepartmentInfo", "Major", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DepartmentName")
                                .HasColumnType("integer")
                                .HasColumnName("DepartmentName");

                            b1.Property<int>("FacultyName")
                                .HasColumnType("integer")
                                .HasColumnName("FacultyName");

                            b1.HasKey("StudentId");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsMany("Backend.Entities.DepartmentInfo", "Minors", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DepartmentName")
                                .HasColumnType("integer")
                                .HasColumnName("DepartmentName");

                            b1.Property<int>("FacultyName")
                                .HasColumnType("integer")
                                .HasColumnName("FacultyName");

                            b1.HasKey("StudentId", "Id");

                            b1.ToTable("Students_Minors");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsOne("Backend.Entities.SemesterInfo", "PreferredSemester", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AcademicYear")
                                .HasColumnType("text");

                            b1.Property<int>("Semester")
                                .HasColumnType("integer");

                            b1.HasKey("StudentId");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("Major");

                    b.Navigation("Minors");

                    b.Navigation("PreferredSemester");
                });

            modelBuilder.Entity("Backend.Entities.AppUser", b =>
                {
                    b.Navigation("DomainUser");
                });

            modelBuilder.Entity("Backend.Entities.CTEForm", b =>
                {
                    b.Navigation("TransferredCourseGroups");
                });

            modelBuilder.Entity("Backend.Entities.DomainUser", b =>
                {
                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");
                });

            modelBuilder.Entity("Backend.Entities.LoggedTransferredCourse", b =>
                {
                    b.Navigation("TransferredCourseGroups");
                });

            modelBuilder.Entity("Backend.Entities.PreApprovalForm", b =>
                {
                    b.Navigation("RequestedCourseGroups");
                });

            modelBuilder.Entity("Backend.Entities.RequestedCourseGroup", b =>
                {
                    b.Navigation("RequestedCourses");
                });

            modelBuilder.Entity("Backend.Entities.TransferredCourseGroup", b =>
                {
                    b.Navigation("TransferredCourses");
                });

            modelBuilder.Entity("Backend.Entities.ExchangeCoordinator", b =>
                {
                    b.Navigation("ToDoList");
                });

            modelBuilder.Entity("Backend.Entities.Student", b =>
                {
                    b.Navigation("CTEForms");

                    b.Navigation("EquivalenceRequestForms");

                    b.Navigation("PreApprovalForms");

                    b.Navigation("ToDoList");
                });
#pragma warning restore 612, 618
        }
    }
}
